/* ANARCHISM.AFRICA — Content Queue v2
 *
 * Publisher / Editor review UI for the auto-scraper pipeline.
 *
 * Tabs:
 *   SCRAPED    — items from content_queue (status=pending). Approve → published.
 *   AI DRAFTS  — articles generated by /api/cron/generate-articles (Supabase
 *                content table, status=pending, created_by=cron:generate-articles).
 *                Approve → status='published', visible on public site immediately.
 *
 * Card features:
 *   - Thumbnail preview (og:image scraped by the cron)
 *   - Tag chips
 *   - "Write article about this →" — pre-fills Article Lab topic
 *   - Inline edit of title + summary before approving
 *   - Open source ↗
 *   - Approve / Reject
 *
 * Mounts into #view-content-queue. Used by publisher.html + editor.html.
 */
(function () {
  const KIND_LABELS = { article:'Article', film:'Film', event:'Event', song:'Song', book:'Book', merch:'Merch', grant:'Grant' };
  const KIND_ORDER  = ['article','film','event','song','book','merch','grant'];

  const $  = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => Array.from(r.querySelectorAll(s));
  const esc = s => String(s==null?'':s).replace(/[&<>"]/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));

  let state = { scraped:[], aiDrafts:[], filter:'all', tab:'scraped', loading:false, role:'publisher' };

  // ── template ──────────────────────────────────────────────────────────────
  function template () {
    return `
      <div class="cq-header panel">
        <div style="display:flex;align-items:baseline;gap:12px;flex-wrap:wrap">
          <h2 style="margin:0">Editorial Queue</h2>
          <span class="mono cq-counts" style="font-size:.72rem;color:var(--muted)"></span>
        </div>
        <p style="color:var(--fg-dim);max-width:68ch;margin:6px 0 12px;font-size:.9rem">
          The RSS scanner pulls from <b>35 curated feeds</b> every day at 06:00 UTC —
          afro-anarchist, pan-African, decolonial, music, film, book publishers.
          The AI composer runs at 09:00 UTC and writes a full draft on the trending theme.
          Nothing goes public without your approval.
        </p>

        <div class="cq-tab-row">
          <button class="cq-tab active" data-cq-tab="scraped">
            <svg viewBox="0 0 20 20"><circle cx="10" cy="10" r="8" stroke="currentColor" stroke-width="1.5" fill="none"/><path d="M6 10l3 3 5-5" stroke="currentColor" stroke-width="1.5" fill="none"/></svg>
            Scraped
            <span class="cq-tab-count" id="cq-count-scraped">—</span>
          </button>
          <button class="cq-tab" data-cq-tab="aiDrafts">
            <svg viewBox="0 0 20 20"><path d="M4 5h12M4 9h9M4 13h7M4 17h5" stroke="currentColor" stroke-width="1.5" fill="none" stroke-linecap="round"/></svg>
            AI Drafts
            <span class="cq-tab-count" id="cq-count-ai">—</span>
          </button>
        </div>

        <div style="display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-top:10px">
          <button class="btn primary" id="cq-refresh">↻ Refresh</button>
          <button class="btn ghost"   id="cq-trigger-scan">Run scan now</button>
          <button class="btn ghost"   id="cq-trigger-articles">Generate article now</button>
          <span id="cq-status" class="mono" style="font-size:.75rem;color:var(--muted);margin-left:4px"></span>
        </div>

        <div id="cq-filters" style="display:flex;gap:6px;flex-wrap:wrap;margin-top:10px">
          <button class="cq-filter active" data-kind="all">All kinds</button>
          ${KIND_ORDER.map(k=>`<button class="cq-filter" data-kind="${k}">${KIND_LABELS[k]}s</button>`).join('')}
        </div>
      </div>

      <div id="cq-items" style="display:flex;flex-direction:column;gap:10px"></div>`;
  }

  // ── boot ──────────────────────────────────────────────────────────────────
  function paint (role) {
    state.role = role || 'publisher';
    const root = $('#view-content-queue');
    if (!root) return;
    if (!root.dataset.painted) {
      root.innerHTML = template();
      root.dataset.painted = '1';
      bind(root);
    }
    refresh();
  }

  function bind (root) {
    root.querySelector('#cq-refresh').addEventListener('click', refresh);
    root.querySelector('#cq-trigger-scan').addEventListener('click', () => triggerStage('scan'));
    root.querySelector('#cq-trigger-articles').addEventListener('click', () => triggerStage('articles'));

    root.querySelector('.cq-tab-row').addEventListener('click', e => {
      const t = e.target.closest('.cq-tab'); if (!t) return;
      $$('.cq-tab', root).forEach(x => x.classList.toggle('active', x===t));
      state.tab = t.dataset.cqTab;
      renderItems();
    });

    root.querySelector('#cq-filters').addEventListener('click', e => {
      const b = e.target.closest('.cq-filter'); if (!b) return;
      $$('.cq-filter', root).forEach(x => x.classList.toggle('active', x===b));
      state.filter = b.dataset.kind;
      renderItems();
    });

    root.addEventListener('click', e => {
      const card = e.target.closest('[data-cq-id]'); if (!card) return;
      const id = card.dataset.cqId;
      const isAI = card.dataset.cqSource === 'ai';
      if (e.target.closest('[data-act="approve"]'))     isAI ? approveAI(id) : approveScraped(id);
      if (e.target.closest('[data-act="reject"]'))      isAI ? rejectAI(id)  : rejectScraped(id);
      if (e.target.closest('[data-act="edit"]'))        toggleEdit(card);
      if (e.target.closest('[data-act="save"]'))        saveEdits(card, id, isAI);
      if (e.target.closest('[data-act="open"]'))        openSource(card);
      if (e.target.closest('[data-act="write-article"]')) writeArticle(card);
    });
  }

  // ── data loading ──────────────────────────────────────────────────────────
  async function refresh () {
    if (state.loading) return;
    state.loading = true; status('Loading…');
    try {
      const [qRes, aiRes] = await Promise.allSettled([
        fetch('/api/content/queue?limit=200', { cache:'no-store' }).then(r=>r.json()),
        fetch('/api/content/list?status=pending&kind=article&limit=100', { cache:'no-store' }).then(r=>r.json())
      ]);
      state.scraped  = qRes.status  === 'fulfilled' ? (qRes.value.items  || []) : [];
      state.aiDrafts = aiRes.status === 'fulfilled' ? (aiRes.value.items || []) : [];

      const sc = document.getElementById('cq-count-scraped');
      const ai = document.getElementById('cq-count-ai');
      if (sc) sc.textContent = state.scraped.length;
      if (ai) ai.textContent = state.aiDrafts.length;
      const cq = document.querySelector('.cq-counts');
      if (cq) cq.textContent = `${state.scraped.length} scraped · ${state.aiDrafts.length} AI drafts`;

      status(state.scraped.length + state.aiDrafts.length > 0 ? 'Ready' : 'Queues empty — cron runs 06:00 + 09:00 UTC', 'ok');
      renderItems();
    } catch (e) { status('Load error: ' + e.message, 'error'); }
    finally { state.loading = false; }
  }

  async function triggerStage (stage) {
    status(`Running ${stage}…`);
    const endpoints = { scan: '/api/cron/scan-content', articles: '/api/cron/generate-articles' };
    const url = endpoints[stage]; if (!url) return;
    try {
      const r = await fetch(url, { method:'GET' });
      const d = await r.json();
      if (!r.ok) throw new Error(d.error || 'HTTP ' + r.status);
      if (stage === 'scan')     status(`Scan done — scanned ${d.scanned}, queued ${d.queued}, og-scraped ${d.og_scraped||0}`, 'ok');
      if (stage === 'articles') status(`Article drafted: "${d.title || '?'}" (${d.status || '?'})`, 'ok');
      setTimeout(refresh, 800);
    } catch (e) {
      status(`${stage} failed — needs CRON_SECRET or runs on schedule. Error: ${e.message}`, 'error');
    }
  }

  // ── rendering ─────────────────────────────────────────────────────────────
  function renderItems () {
    const host = $('#cq-items'); if (!host) return;
    const list = state.tab === 'scraped' ? state.scraped : state.aiDrafts;
    const filtered = state.filter === 'all' ? list : list.filter(x => x.kind === state.filter);

    if (!filtered.length) {
      host.innerHTML = `<div class="panel"><p style="color:var(--muted);margin:0">
        ${state.tab === 'scraped'
          ? 'No scraped items pending. The cron runs at 06:00 UTC daily — or hit "Run scan now" above.'
          : 'No AI drafts pending. The article generator runs at 09:00 UTC — or hit "Generate article now" above.'}
      </p></div>`;
      return;
    }
    host.innerHTML = filtered.map(it =>
      state.tab === 'scraped' ? scrapedCard(it) : aiDraftCard(it)
    ).join('');
  }

  // ── scraped card ──────────────────────────────────────────────────────────
  function scrapedCard (it) {
    const kind  = KIND_LABELS[it.kind] || it.kind || '?';
    const date  = it.published_at ? new Date(it.published_at).toLocaleDateString('en-GB', {day:'numeric',month:'short',year:'numeric'}) : '';
    const tags  = (it.tags || []).slice(0, 6).map(t=>`<span class="cq-tag">${esc(t)}</span>`).join('');
    const imgSrc = it.image || '';
    return `
      <div class="panel cq-card" data-cq-id="${esc(it.id)}" data-cq-source="scraped">
        <div class="cq-card-inner">
          ${imgSrc ? `<div class="cq-thumb" style="background-image:url('${esc(imgSrc)}')"></div>` : `<div class="cq-thumb cq-thumb--empty"><span class="mono">${esc(kind[0]||'?')}</span></div>`}
          <div class="cq-card-body">
            <div class="cq-card-meta mono">
              <span class="cq-kind-badge">${esc(kind.toUpperCase())}</span>
              <span style="color:var(--muted)">${esc(it.source||'')}</span>
              ${date ? `<span style="color:var(--muted)">${date}</span>` : ''}
            </div>
            <h3 class="cq-card-title">
              <span class="cq-view">${esc(it.title||'(untitled)')}</span>
              <input class="cq-edit" type="text" value="${esc(it.title||'')}" data-field="title" style="display:none"/>
            </h3>
            <p class="cq-view cq-summary">${esc((it.summary||'').slice(0,320))}${(it.summary||'').length>320?'…':''}</p>
            <textarea class="cq-edit" data-field="summary" style="display:none">${esc(it.summary||'')}</textarea>
            ${tags ? `<div class="cq-tags">${tags}</div>` : ''}
            ${it.url ? `<a data-link="${esc(it.url)}" class="cq-source-link mono">${esc((it.source||'source') + ' ↗')}</a>` : ''}
          </div>
          <div class="cq-card-actions">
            <button class="btn primary"  data-act="approve">Approve ✓</button>
            <button class="btn ghost"    data-act="write-article" title="Pre-fill Article Lab with this topic">Write article →</button>
            <button class="btn ghost"    data-act="edit">Edit</button>
            <button class="btn ghost"    data-act="save"  style="display:none">Save edits</button>
            <button class="btn ghost"    data-act="open">Open source ↗</button>
            <button class="btn cq-reject" data-act="reject">Reject</button>
          </div>
        </div>
      </div>`;
  }

  // ── AI draft card ─────────────────────────────────────────────────────────
  function aiDraftCard (it) {
    const date = it.created_at ? new Date(it.created_at).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}) : '';
    const verifyCount = (it.verify_notes||[]).length;
    const sourcesCount = (it.sources_cited||[]).length;
    const readingTime = it.reading_time || Math.max(1, Math.round(((it.body||'').split(/\s+/).length)/220));
    const tags = (it.tags||[]).slice(0,6).map(t=>`<span class="cq-tag">${esc(t)}</span>`).join('');
    const imgSrc = it.image || '';
    const bodyPreview = (it.body||'').replace(/#+\s/g,'').replace(/\[verify\]/gi,'').replace(/\*\*/g,'').slice(0,350);

    return `
      <div class="panel cq-card cq-card--ai" data-cq-id="${esc(it.id)}" data-cq-source="ai">
        <div class="cq-ai-badge mono">AI DRAFT · cron:generate-articles · ${date}</div>
        <div class="cq-card-inner">
          ${imgSrc ? `<div class="cq-thumb" style="background-image:url('${esc(imgSrc)}')"></div>` : `<div class="cq-thumb cq-thumb--ai"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9" stroke="currentColor" fill="none" stroke-width="1.5"/><path d="M8 10v4M16 10v4M9 16c1.6 1.2 4.4 1.2 6 0" stroke="currentColor" stroke-width="1.5" fill="none"/></svg></div>`}
          <div class="cq-card-body">
            <div class="cq-card-meta mono">
              <span class="cq-kind-badge cq-kind-badge--ai">ARTICLE</span>
              <span style="color:var(--muted)">${readingTime}min read</span>
              ${verifyCount ? `<span class="cq-verify-warn">${verifyCount} [verify] flags</span>` : ''}
              ${sourcesCount ? `<span style="color:var(--muted)">${sourcesCount} sources</span>` : ''}
            </div>
            <h3 class="cq-card-title">
              <span class="cq-view">${esc(it.title||it.deck||'(untitled draft)')}</span>
              <input class="cq-edit" type="text" value="${esc(it.title||'')}" data-field="title" style="display:none"/>
            </h3>
            ${it.deck ? `<p class="cq-deck">${esc(it.deck)}</p>` : ''}
            <p class="cq-view cq-summary cq-body-preview">${esc(bodyPreview)}${bodyPreview.length>=350?'…':''}</p>
            ${verifyCount ? `<div class="cq-verify-list">${(it.verify_notes||[]).map(v=>`<div class="cq-verify-item">⚑ ${esc(v)}</div>`).join('')}</div>` : ''}
            ${tags ? `<div class="cq-tags">${tags}</div>` : ''}
          </div>
          <div class="cq-card-actions">
            <button class="btn primary"  data-act="approve">Publish ✓</button>
            <button class="btn ghost"    data-act="edit">Edit title</button>
            <button class="btn ghost"    data-act="save"  style="display:none">Save</button>
            <button class="btn cq-reject" data-act="reject">Discard</button>
          </div>
        </div>
      </div>`;
  }

  // ── actions ───────────────────────────────────────────────────────────────
  function toggleEdit (card) {
    const on = card.dataset.editing === '1';
    card.dataset.editing = on ? '' : '1';
    card.querySelectorAll('.cq-view').forEach(el => el.style.display = on ? '' : 'none');
    card.querySelectorAll('.cq-edit').forEach(el => el.style.display = on ? 'none' : '');
    card.querySelector('[data-act="save"]').style.display = on ? 'none' : '';
    card.querySelector('[data-act="edit"]').textContent = on ? 'Edit' : 'Cancel';
  }

  async function saveEdits (card, id, isAI) {
    const patch = {};
    card.querySelectorAll('.cq-edit').forEach(el => { if (el.value !== undefined) patch[el.dataset.field] = el.value; });
    status('Saving…');
    try {
      const url  = isAI ? '/api/content/save' : '/api/content/queue';
      const body = isAI ? { id, ...patch } : { action:'edit', id, patch };
      const r = await fetch(url, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify(body) });
      const d = await r.json();
      if (!r.ok) throw new Error(d.error || 'save failed');
      status('Saved ✓', 'ok'); refresh();
    } catch (e) { status('Save error: ' + e.message, 'error'); }
  }

  async function approveScraped (id) {
    if (!confirm('Approve this item and publish it to the public site?')) return;
    status('Publishing…');
    try {
      const r = await fetch('/api/content/queue', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({action:'approve',id}) });
      const d = await r.json(); if (!r.ok) throw new Error(d.error||'approve failed');
      status('Published ✓', 'ok'); refresh();
    } catch (e) { status('Error: ' + e.message, 'error'); }
  }

  async function rejectScraped (id) {
    if (!confirm('Remove this item from the queue?')) return;
    try {
      const r = await fetch('/api/content/queue', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({action:'reject',id}) });
      const d = await r.json(); if (!r.ok) throw new Error(d.error||'reject failed');
      status('Rejected', 'ok'); refresh();
    } catch (e) { status('Error: ' + e.message, 'error'); }
  }

  async function approveAI (id) {
    if (!confirm('Publish this AI-generated article?\n\nMake sure you have checked all [verify] flags.')) return;
    status('Publishing…');
    try {
      const r = await fetch('/api/content/save', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({id, status:'published', published_at: new Date().toISOString()}) });
      const d = await r.json(); if (!r.ok) throw new Error(d.error||'publish failed');
      status('Published ✓', 'ok'); refresh();
    } catch (e) { status('Error: ' + e.message, 'error'); }
  }

  async function rejectAI (id) {
    if (!confirm('Discard this AI draft?')) return;
    try {
      const r = await fetch('/api/content/save', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({id, status:'rejected'}) });
      const d = await r.json(); if (!r.ok) throw new Error(d.error||'reject failed');
      status('Discarded', 'ok'); refresh();
    } catch (e) { status('Error: ' + e.message, 'error'); }
  }

  function openSource (card) {
    const a = card.querySelector('a[data-link]');
    if (a) window.open(a.dataset.link, '_blank', 'noopener');
  }

  function writeArticle (card) {
    const title = card.querySelector('.cq-card-title .cq-view')?.textContent || '';
    const src   = card.querySelector('a[data-link]')?.dataset.link || '';
    // Pre-fill Article Lab and switch to it
    const topicInput = document.getElementById('al-topic');
    if (topicInput) {
      topicInput.value = title || '';
      // Switch to articlelab view if possible
      const btn = document.querySelector('[data-view="articlelab"]');
      btn?.click();
    } else {
      // Fallback: navigate with query param
      const base = document.body.dataset.role === 'editor' ? 'editor.html' : 'publisher.html';
      location.href = `${base}?view=articlelab&topic=${encodeURIComponent(title)}`;
    }
  }

  function status (msg, kind='idle') {
    const el = document.getElementById('cq-status'); if (!el) return;
    el.textContent = msg;
    el.style.color = kind==='error' ? 'var(--red,#e55)' : kind==='ok' ? 'var(--green,#4a4)' : 'var(--muted)';
  }

  window.ContentQueue = { render: paint };
})();
